# Generated by Django 3.1.5 on 2021-01-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_cat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_category',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_category',
            field=models.ManyToManyField(null=True, to='movie_cat.Category', verbose_name='Категория'),
        ),
    ]
